### ISSUE TITLE
Install UI library

### ISSUE THREAD

**Issue by marchchad** [marchchad/dadwind#1]
Last discussion was to use Material-UI.

Install Material-UI and set up basic navigation.
Ideally we can set up theme support (dark mode) sooner than later.

**Comment by Gruzzly-bear** [comment]
Will work on basic navigation within the next few days, but we can strike off the set up of material UI. Perhaps open a new issue regarding Navigation specifically.

**Comment by marchchad** [comment]
Moving navigation component development to a new issue and assigning to @Gruzzly-bear
